# Generated by Django 5.0.1 on 2024-01-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(blank=True, max_length=12, null=True)),
                ('instagram', models.CharField(blank=True, max_length=12, null=True)),
                ('twitter', models.CharField(blank=True, max_length=12, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=12, null=True)),
                ('photo_main', models.ImageField(upload_to='agent/%Y%m%d/')),
                ('hired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mvp', models.BooleanField(default=False)),
            ],
        ),
    ]
