# Generated by Django 5.0.1 on 2024-01-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('title', models.TextField(blank=True, null=True)),
                ('amount', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Short Let', 'Short Let')], max_length=50)),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='testimony/%Y%m%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='testimony/%Y%m%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
