# Generated by Django 5.0.1 on 2024-01-23 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Short Let', 'Short Let')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('listing_id', models.IntegerField(default=6814, unique=True)),
                ('listing_type', models.CharField(choices=[('House', 'House'), ('Land', 'Land')], max_length=150)),
                ('title', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('toilets', models.IntegerField(blank=True, null=True)),
                ('garage', models.IntegerField(blank=True, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Sold', 'Sold'), ('Rented', 'Rented'), ('Available', 'Available')], max_length=150)),
                ('furnish', models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Funished'), ('Not Furnished', 'Not Furnished')], max_length=150, null=True)),
                ('photo_main', models.ImageField(upload_to='listing/%Y%m%d/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='listing/%Y%m%d/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='listing/%Y%m%d/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='listing/%Y%m%d/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='listing/%Y%m%d/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='listing/%Y%m%d/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='listing/%Y%m%d/')),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to='listing/%Y%m%d/')),
                ('photo_8', models.ImageField(blank=True, null=True, upload_to='listing/%Y%m%d/')),
                ('photo_9', models.ImageField(blank=True, null=True, upload_to='listing/%Y%m%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.category')),
            ],
        ),
    ]
