# Generated by Django 5.0.1 on 2024-01-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.IntegerField(default=5676, unique=True),
        ),
    ]
