# Generated by Django 5.0.1 on 2024-01-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='listing_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
